export const ACTIONS = {
  FACE_IMAGE_SELECTED: 'FACE_IMAGE_SELECTED',
  DOCUMENT_IMAGE_SELECTED: 'DOCUMENT_IMAGE_SELECTED',
  UPLOAD_START: 'UPLOAD_START',
  UPLOAD_FACE: 'UPLOAD_FACE',
  UPLOAD_DOC: 'UPLOAD_DOC',
  VERIFICATION_COMPLETE: 'VERIFICATION_COMPLETE',
  VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
  VERIFICATION_ERROR: 'VERIFICATION_ERROR',
};

export type action = {
  type: string,
  event?: any,
  validation?: any,
};
